using dotnetConf2023.Shared.Models;

namespace dotnetConf2023.Shared.Services
{
    public class SpeakerService
    {
        public IEnumerable<SpeakerModel> GetSpeakers()
        {
            var speakers = new List<SpeakerModel> {
                new SpeakerModel {
                    Id = "John Chang",
                    Name = "張書源",
                    JobTitle = "台灣微軟 客戶成功事業群副總經理",
                    PictureUrl ="./img/speakers/John Chang-2.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前擔任 Microsoft 台灣微軟客戶成功事業群 副總經理，對於雲端服務架構以及商務應用發展具有多年實務經驗，也持續致力於推廣人工智能在產業方面的應用。曾經擔任全球雲端合作戰略官、雲端與人工智能應用架構師、企業應用整合顧問以及講師。專注在雲端服務以及與企業應用程式整合的相關技術，以及與技術社群的合作。",
                    Topic = "Opening",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 0, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Will Huang",
                    Name = "Will 保哥",
                    JobTitle = "多奇數位創意 技術總監",
                    PictureUrl ="./img/speakers/Will 保哥.jpg",
                    BlogUrl = "http://blog.miniasp.com/",
                    FacebookUrl = "https://www.facebook.com/will.fans/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任「多奇數位創意有限公司」技術總監。2018 年榮獲 Angular 方向的 Google Developer Expert (GDE) 開發專家。連續 14 度當選微軟最有價值專家(MVP)。2019 獲選微軟技術社群區域總監 (Microsoft Regional Director)。熟悉 Angular、JavaScript、.NET、C#、ASP.NET MVC、Go、Docker、Kubernetes 相關技術。擅長 DevOps 與組織文化建立、軟體團隊建構與管理。熱愛分享知識。",
                    Topic = "ASP.NET Core 7 全新功能探索",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 15, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 15, 50, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "David Tung",
                    Name = "David Tung",
                    JobTitle = "光岩資訊資深技術顧問",
                    PictureUrl ="./img/speakers/David Tung.jpg",
                    BlogUrl = "http://studyhost.blogspot.tw/",
                    FacebookUrl = "http://www.facebook.com/DotNetWalker/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "光岩資訊資深技術顧問、歷屆微軟 TechDays、TechED 研討會講師、連續 14 年榮獲微軟最有價值專家 (MVP)、LINE API Expert(LAE)，專長領域跨及.NET開發技術、Azure DevOps、AI、ChatBot...熟悉 BPM、APS、ERP…等企業應用資訊系統之建置與導入。David 是敏捷開發與 DevOps 的熱愛者，打從 Apple II 時代開始闖蕩江湖至今，在資訊業各領域均有參與。做過 MIS/IT、當過 RD、帶過專案、團隊、也賣過軟體，寫過（這年頭已經消失了的）雜誌專欄、長年擔任企業訓練講師與顧問，出過一堆書……打從沒有物件導向，沒什麼所謂軟體生命週期管理的年代，一路經歷了無數個壯觀的大小瀑布與千瘡百孔的雷與坑、一直到今天，依舊還是一個喜歡寫 Code 的人...",
                    Topic = "董事長群星論壇",
                    TopicOutline = "由江湖人稱郭董的 Edward 與董董 (David) 跟大家分享今天所有場次的心得，並總結 2022 的 .NET Conf 的看法",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 16, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 16, 50, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Edward Kuo",
                    Name = "Edward Kuo",
                    JobTitle = "Kingston IT Manager",
                    PictureUrl ="./img/speakers/Edward Kuo.jpg",
                    BlogUrl = "https://profile.edwardkuo.dev/",
                    FacebookUrl = "https://www.facebook.com/groups/286316594814216/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "是 Enterprise IT Manager、 Microsoft Regional Director、Microsoft Azure MVP & Speaker 在不同的角色中學習用不同觀點看待軟體開發流程，不僅熱愛技術，也喜愛探索商業需求，在需求與技術探尋合適的解決方案。現在主要專注於雲端系統架構設計、工業 4.0 以及 AI 解決方案架構與導入，並指導企業建置的 DevOps 開發與維運流程。",
                    Topic = "董事長群星論壇",
                    TopicOutline = "由江湖人稱郭董的 Edward 與董董 (David) 跟大家分享今天所有場次的心得，並總結 2022 的 .NET Conf 的看法",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 16, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 16, 50, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Andrew Wu",
                    Name = "Andrew Wu",
                    JobTitle = "91APP 首席架構師",
                    PictureUrl ="./img/speakers/Andrew Wu-3.jpg",
                    BlogUrl = "https://columns.chicken-house.net/",
                    FacebookUrl = "https://www.facebook.com/andrew.blog.0928/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任 91APP 首席架構師，專長領域為軟體工程、物件導向設計、分散式系統架構設計、平行處理、API 設計及微服務導向架構設計（microservices）等。具 23 年 Microsoft .NET Framework、SaaS、B2B2C 等雲端服務開發經驗，喜歡研究各種技術背後的原理與實作細節。現任職之 91APP 為台灣首間上櫃之 SaaS 服務商，具逾500人的營運團隊，為零售產業數位轉型的軍火庫，提供企業級軟體雲產品到品牌經營顧問之服務。Andrew 樂於分享技術新知與開發經驗，除了時常出席各大技術研討會與社群活動外；也不時更新部落格文章，與夥伴們交流與傳承經驗，深信自我精進源自分享，這也是 20 年持續筆耕不輟的動力。",
                    Topic = "API First - 從理想的 API Spec 設計開始",
                    TopicOutline = "之前的研討會，我談了 API First 的開發策略，在這年代大家都知道 API 很重要了，但是當你要開始動手寫 API 時，是否碰過不知道怎麼開規格的窘境?我在工作上面對了不少需要開出高品質的 API 規格需求，因為 API 的規格遠比實做還來的重要啊，良好的 API 設計能帶來良好的開發體驗 (DX)，也能引導使用你的 API 的應用程式用正確的邏輯來存取你的服務，正所謂 \"好的 API (規格) 帶你上天堂\"，這個場次，我想花點時間，來說明我常用的設計方法: 狀態機。API 的規格，濃縮了你的服務所有面向的需求，一不小心很容易弄出符合規格但是不合理的操作。RESTful API 通常背後都代表了某種要操作的 resource, 而狀態機是控制 resource 的生命週期最理想的方式。因此從狀態機來推導 API 的指令，允許執行的條件，控制資源的生命週期，授權管控，以及對應的事件等等，再適合也不過了。這個場次我會用實際的案例，帶著大家從狀態機的設計，一路推演到實際的 API 規格，同時用 ASP.NET Core WebAPI 完整的實做出來。如果你聽完意猶未盡，也歡迎你繼續聽下一場 “API Client SDK 的開發技巧(待確認)”。好的 API 搭配好的 Client SDK，能進一步地讓你用你熟悉的程式語言 (我們用 C# 為例)，充分發揮語言的優點來存取 API。這場次會延續同樣的範例，由我的同事 Evance Kao 帶來的精采分享",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 12, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 12, 50, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Jian Hui",
                    Name = "盧建暉",
                    JobTitle = "微軟全技術棧佈道師",
                    PictureUrl ="./img/speakers/Jian Hui.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "微軟 Regional Cloud Advocate ，全技術棧佈道師，專注在人工智慧、物聯網、雲原生領域。",
                    Topic = "用 .NET 啟動你的無人機",
                    TopicOutline = ".NET 是一個跨平台，跨應用場景的開源技術，我們一直希望用一種程式語言一個體系打造全方位的方案。本次課程我們通過無人機，展示如果通過 .NET 來打造一個從雲到端的解決方案，涉及內容包括原型應用，前端應用，人工智慧，以及雲端實現。希望給大家一個完整的 .NET 開發的故事",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 16, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 16, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Duran Hsieh",
                    Name = "謝政廷",
                    JobTitle = "Site Reliability Engineer",
                    PictureUrl ="./img/speakers/Duran Hsieh.jpg",
                    BlogUrl = "http://dog0416.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/duran.alfine",
                    TwitterUrl = "https://twitter.com/duranalfine",
                    LinkedinUrl = "https://www.linkedin.com/in/duran-hsieh-4b65a688/",
                    Introduction = "遊走於開發、DevOps、SRE 領域的工程師",
                    Topic = "WatchDog: An open-source, lightweight, real-time logger for ASP.NET",
                    TopicOutline = "WatchDog 是一個開放原始碼、即時日誌紀錄器且輕量級 ASP.NET Log Library。它提供了互動式儀表板，讓使用者可以排序、過濾與搜尋應用程式日誌(Message 與 Event)、HTTP Request 與 Response。WatchDog 透過 SignalR 進行即時監控，並使用 LiteDB 資料庫 (類似 Serverless MongoDB 資料庫)進行記錄，套件大小只有 600 KB。來參加這場議程，一起來認識 WatchDog 吧!!",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 10, 30, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 11, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Bruce Chen",
                    Name = "Bruce Chen",
                    JobTitle = "Kingston Senior Engineer",
                    PictureUrl ="./img/speakers/Bruce Chen-2.jpg",
                    BlogUrl = "https://blog.kkbruce.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "任職於全美前 50 大私人企業。SkillTree.my、微軟 TechDays、MSDN 講座、Azure Bootcamp 講師，於 ASP.NET MVC 2.0 接觸 MVC 架構，從此愛上 MVC 推廣 MVC，對於 ASP.NET Web API 框架也有深入研究，是宣導 ASP.NET Web API 的先驅。2013 年先後加入 STUDY4 與 twMVC 社群核心講師，不定期分享開發技術與經驗。出版作品有《ASP.NET MVC4 網站開發美學》、《ASP.NET MVC 5網站開發美學》、《ASP.NET MVC 5 网站开发之美》。對於開發人員最頭疼的前端 Layout 問題，翻譯《Bootstrap 2》《Bootstrap 3》繁體中文文件更是學習 Bootstrap 的必讀資料。",
                    Topic = "K8s 地端平台架設大補帖：minikube、MicroK8s、Kubernetes 全攻略",
                    TopicOutline = "雲端平台很好很方便，點選之間許多複雜的環境頂多幾分鐘幫你架設完成。但是，因公司網路有著先天限制，在導入各種技術平台方案時都需要能獨立網路及地端執行。在導入地端 Kubernetes 的過程中，講者習慣會先在自己的筆電架設，以模擬一個獨立執行環境，確認落地運作的可行性。想不到在本機架設 Kubernetes Cluster 的過程卻困難重重。本場次分享如何在地端（以筆電 Hyper-V 環境為例）由入門到進階的幾種 Kubernetes 架設方式，以及落地 Kubernetes 架設過程應注意的相關事項，為你的 .NET 應用程式打造最先進的容器協調大平台。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 10, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 10, 50, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Kevin Yang",
                    Name = "Kevin Yang",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Kevin Yang.jpg",
                    BlogUrl = "https://blog.kevinyang.net/",
                    FacebookUrl = "https://www.facebook.com/CKNotepad/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前擔任 Angular Taiwan、Angular Girls Taiwan 、TypeScript Taiwan 社群管理者，Angular 線上讀書會主持人。2018 年榮獲 Angular/Web GDE (Google Developer Expert) 開發專家。微軟最有價值專家 (Visual Studio and Development Technologies)。熱衷分享任何新奇的技術資訊、不務正業(跨領域)，目前已跨入的領域有會計、醫療資訊及程式開發。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 10, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 10, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Jimmy Ho",
                    Name = "Jimmy Ho",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Jimmy Ho.jpg",
                    BlogUrl = "https://jiaming0708.github.io/",
                    FacebookUrl = "https://www.facebook.com/secretgogoworld",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個熱愛學習、分享並且近期狂點前端技能樹的小小工程師，什麼都會什麼都不奇怪。",
                    Topic = "一次搞懂 Blazor CSS 眉腳",
                    TopicOutline = "開發網頁的時候，CSS一直是我們的好朋友，但也是我們最恨的地方，沒弄清楚的話往往都會在上面哉跟頭，今天讓我們一次搞清楚 Blazor 的一些眉腳",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 12, 30, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Gelis Wu",
                    Name = "Gelis Wu",
                    JobTitle = "集英信誠資深 .NET 技術顧問",
                    PictureUrl ="./img/speakers/Gelis Wu.jpg",
                    BlogUrl = "http://gelis-dotnet.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/groups/361804473860062/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "我是 Gelis，從事軟體專案開發相關工作已經 20 餘年（顧問工作5年、專案開發 15 年），我熱愛軟體工程、UML 系統分析與設計，擅長 OO 物件導向分析與設計，也擅長將『使用者需求』並尋求一種將需求最佳化『軟體架構設計』的設計樣式。 目前任職資深技術顧問，目前主要負責與 .NET 相關的開發、顧問、訓練工作。<br>曾經連任七屆微軟最有價值專家 MVP (2011 ~ 2017)，有個人的技術部落格 『Gelis 技術隨筆』，以記錄在技術上學習的新知與個人的研究發表。",
                    Topic = ".NET 7 升級教戰手冊",
                    TopicOutline = "Agenda<br/>● 升級前的前置作業<br/>        - .NET 6 LTS / .NET 7 STS<br/>● 專案檔升級 (談 upgrade-assistant)<br/>● 專案使用的第三方套件注意事項<br/>● Web.Config/Appsettings 的升級小技巧<br/>        - 客製化 Configuration.AppSettings[index] 讓升級衝擊降低<br/>● 如何升級 EntityFrameworkCore？<br/>        - 客製化缺少的相關擴充方法降低升級的衝擊<br/>● 將 Newtonsoft.Json 改為 System.Text.Json<br/>● Others: 其他 Middleware (Startup) 注意事項",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 14, 30, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 15, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Bao Chengyou",
                    Name = "鮑承佑",
                    JobTitle = "GranDen 狂點軟體 CTO",
                    PictureUrl ="./img/speakers/鮑承佑.jpg",
                    BlogUrl = "https://linktr.ee/windperson",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "講師於 2014 年投入遊戲業，2018 年起在一家 AR/VR/XR 相關遊戲、商務應用開發的新創公司擔任 CTO；Xamarin, ASP.NET Core 等前後端開發技術都略懂略懂，但抓 bug 比較在行。",
                    Topic = "ASP .NET Core 7家族新成員也是老戰友：Microsoft Orleans v7 介紹",
                    TopicOutline = "Microsoft Orleans（以下簡稱Orleans）是一個MIT授權的開源分散式運算框架，可讓開發者以較輕量的心智模型 Virtual Actor Model 的概念下，開發互動複雜且高併發的分散式應用。<br/>在 .NET 7前是獨立發布的開源專案，從 .NET 7 開始，成為 ASP .NET Core 7 官方首選的後端資料狀態/快取層解決方案。<br/>本議程介紹 Orleans 主要幾個核心功能來介紹如何入門 Orleans 開發架構，並以開發/維運這兩個不同角度來介紹，在開發時期如何拆解系統架構來套用 Orleans 框架、撰寫測試和除錯；在維運時依據不同流量規模以及是否需要 24/7(全天營運)的運營策略考量下，Orleans 應用要部署在 Azure 非容器化的 PaaS 服務抑或用 K8S 容器化上雲端的幾種方法。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 11, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 11, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Yin Sangzhi",
                    Name = "尹相志",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/尹相志-AI.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "於 2002 年台灣創立 asiaMiner 為台灣第一家專業大數據顧問公司。2015 年正式擔任中國第一家大數據顧問公司華院數據的首席數據科學家，並於 2016 年發起中國首次人工智能大賽 BOT (Brain of things) 2016，目前於大陸成立 Deepbelief.ai 聚焦於機器視覺的創新商業應用。",
                    Topic = "運用 ONNX 建構高效的 AIOT 邊緣計算應用",
                    TopicOutline = "在這場演講中，將會介紹卷積層融合以及重參數化等機制進行深度學習模型的無損壓縮，以及我將以自動駕駛的街景分割為案例，運用 ONNX Runtime 結合 .NET 開發高效能的邊緣計算應用",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 14, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 14, 50, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KO KO",
                    Name = "KO KO",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KO KO.jpg",
                    BlogUrl = "https://magic-panda-engineer.github.io/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Ko Ko 是微軟 AI 領域最有價值專家，同時也是台灣知名的講者。他參與了無數的技術年會演講，包含了 COSCUP、 .NET Conference，ModernWeb，PyCon APAC 等等的大型年會，累計已超過萬名聽眾。其系列文章「一起學習 Azure Machine Learning」是繁體中文圈關於 Azure Machine Learning 最完整的學習資源之一。",
                    Topic = "用 Azure Machine Learning 來做 AI 繪圖",
                    TopicOutline = "Azure Machine Learning 其功能與生態系相當完整，是目前做 AI 研究與應用開發最主流的工具之一。AI 繪圖是最近相當火紅的領域，尤其以 Text to image 這個領域最受歡迎。<br/>本次演講將會聚焦在 Azure Machine Learning 的操作上，如何使用 Stable Diffusion 來做 AI 繪圖，並介紹其原理，然後以 Live Demo 來展示如何撰寫程式碼，以達成  Text to image 的任務。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 14, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 14, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Alan Tsai",
                    Name = "Alan Tsai",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Alan Tsai.jpg",
                    BlogUrl = "https://blog.alantsai.net/",
                    FacebookUrl = "http://fb.alantsai.net/",
                    TwitterUrl = "http://twitter.alantsai.net/",
                    LinkedinUrl = "http://linkedin.alantsai.net/",
                    YouTubeUrl = "http://yt.alantsai.net/",
                    Introduction = "深耕 .NET 軟體開發多年，深信使用的技術不是重點，重點在於如何全面的思考並且用適合的技術解決客戶的問題，為現任的微軟最有價值專家（Microsoft MVP）- Azure，微軟認證講師（MCT），樂於分享，深信教就是最好的學習方式，定期發佈部落格（Alan Tsai 的學習筆記）文章、影片、演講分享或者幫忙翻譯。很宅，除了上班之外會出去應該都是參加/協助社群活動（Azure Taiwan），為現任 Study4.TW 成員之一。除了程式以外，就愛看小說。",
                    Topic = "談 Event Driven Architecture 之前，是不是該把 Event 規格搞定？ CloudEvents 是什麼？ | 邁上 Cloud Native App 之路",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 13, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 13, 50, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "ZhanYixuan",
                    Name = "詹益軒",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/詹益軒.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "我是饅頭 Bruno Jan 在開發技術上熱愛網頁開發相關技術，嫻熟 .NET、ReactJS、容器化、DevOps 以及雲端的開發與維運，因熱愛分享自身所學所以加入 STUDY4 成為核心成員，曾分享自身過往的開發經驗，.NET 的效能調校以及報表伺服器等等。在認證方面具有 CSM、CSD 與 CSPO 認證，也曾獲選兩任 MVP（微軟最有價值專家）。",
                    Topic = "邁向元宇宙部署模式",
                    TopicOutline = "在現代化部署實現後我們的下一步是什麼？當然要邁向再部署與系統開發上有更好的佈局，讓程式碼與環境不再相依，在環境的創造與實現可以更富有彈性。該怎麼做？我們在開發時需要注意些什麼？就讓我用 .net core來實現給你看吧！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 16, 30, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 17, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Marcus",
                    Name = "Marcus Tung",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Marcus Tung.jpg",
                    BlogUrl = "https://marcus116.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/marcus.tung.3",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "後端打雜小弟，10 年以上軟體相關開發經驗，喜歡上技術相關課程、參與外部研討會吸收新知識。",
                    Topic = "再不使用 APM 就芭比Q 了",
                    TopicOutline = "隨著科技與技術不斷的進步與創新，軟體架構從單體式(Monolithic)到 SOA(Service Oriented Architecture) 再到微服務(Micro Service)，在應用程式服務顆粒度切分得更細的情況下，當系統發生問題時也隨著架構複雜度變高更難定位問題，有沒有更好的方案可以解決呢 ? <br/><br/>這個議程將會用淺顯易懂的方式，帶你一起探究下列議題<br/>1. .NET 如何與 Elastic APM 整合<br/>2. Elastic APM 內建的監控數據可以為團隊帶來哪些幫助<br/>3. 如何與現代化遙測標準 OpenTelemetry 整合<br/>透過 Elastic APM 快速了解問題的脈絡(Tracing)，找到可能的系統效能瓶頸，讓發生線上問題時團隊可以更快速定位問題並止血，分享在這過程學習到的經驗以及小小心得。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 15, 30, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 16, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Mike",
                    Name = "黃升煌 Mike",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Mike.jpg",
                    BlogUrl = "https://wellwind.idv.tw/blog/",
                    FacebookUrl = "https://www.facebook.com/fullstackledder",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "多奇數位創意有限公司全端工程師，目前是 Microsoft MVP 及 Angular，熟悉 .NET WebAPI 與 Angular 開發技術，主要於個人部落格分享學習知識，並活躍於 Angular Taiwan Facebook 社團。",
                    Topic = "Tauri - 前端人員也能打造小巧快速的 Windows 應用程式",
                    TopicOutline = "Web 技術要統治世界真的不是說說的，現在到哪裡都可以看得到 web 技術的影子，透過 web 技術打造 Windows 應用程式也早已行之有年，但過去許多工具產出來的應用程式大小都非常龐大，直到 Tauri 的出現提供了我們另外一種選擇，透過 Tauri 我們可以輕易的打造檔案更小、速度更快、也更安全的 Windows 應用程式，而你所要會的，依然還是那些本來就該會的前端開發知識而已！本次分享將帶大家實際看看使用 Tauri 來撰寫 Windows 應用程式是一個怎麼樣的體驗。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 15, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 15, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Chris Liu",
                    Name = "Chris Liu",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Chris Liu.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "前某義大利餐廳行政主廚，曾於兩間台灣金流界龍頭任職，也曾擔任過某電子支付公司研發部主管，現為 Geek & Nerd Studios CEO 喜歡協助客戶完成技術導入，對他而言程式就跟料理一樣 keep learning, keep your knife sharpen。",
                    Topic = "Azure Container Apps",
                    TopicOutline = "想要使用容器化技術<br/>但是因為一些因素無法安裝Docker<br/>又或是覺得K8S很困難嗎？<br/>沒關係來聽聽在下分享的Azure Container Apps<br/>讓我們一起快速上手",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 13, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 13, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Kyle Shen",
                    Name = "Kyle Shen",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Kyle Shen.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "一個跑進設計學院的工程師，曾任 2014-2018 微軟最有價值專家 (Microsoft MVP)，在新創打滾多年後，目前於製造業擔任Product Owner",
                    Topic = "那些年用 Azure Boards 交付過的產品",
                    TopicOutline = "疫情催生遠距辦公模式，異地協作已經變為各產業常態，如何讓團隊瞄準目標，透明化工作事項變為重要課題，Azure DevOps 將開發人員、專案經理和使用者結合在一起, 讓組織以比傳統軟體發展方法更快的反應變化，建立和改善產品。本議程將聚焦多年使用 Azure Boards 來執行 Scurm 框架的經驗，提供一個 Practice 作為交付需求的參考",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 13, 30, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 14, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "James Fu",
                    Name = "James Fu",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/James Fu.jpg",
                    BlogUrl = "https://dotblogs.com.tw/jamesfu",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "主要專長在系統架構設計、資料庫效能調教等實作經驗。在 STUDY4.TW 社群擔任講師，推廣 SQL Server 與 Hyper-V 相關技術，具 MCSE 國際認證執照，獲選為微軟最有價值專家（MVP）。",
                    Topic = "SQL Server 的資料版本",
                    TopicOutline = "介紹 temporal table 和 ledger table 的使用",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 12, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 12, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Poy Chang",
                    Name = "Poy Chang",
                    JobTitle = "Kingston Senior Engineer",
                    PictureUrl ="./img/speakers/Poy Chang.jpg",
                    BlogUrl = "https://poychang.github.io/",
                    FacebookUrl = "https://www.facebook.com/poychang.tech/",
                    TwitterUrl = "https://twitter.com/poychang",
                    LinkedinUrl = "https://www.linkedin.com/in/poychang/",
                    Introduction = "目前任職於全美 100 大私人企業，負責企業內部 IT 解決方案設計與開發，從前端開發到後端系統建構的過程中累積多元技術經驗，目前專注於 Azure 與 .NET 技術研究，經常將經驗發表個人部落格，分享各項技術實務。",
                    Topic = "又小又快值得期待的 NativeAOT",
                    TopicOutline = ".NET 在很多使用情境都表現得可圈可點，在 .NET 5 的時候推出了 Croddgen，也就是 ReadyToRun 的特性，讓 .NET 應用程式從 JIT 轉身一變成了混和式 AOT 策略，而在 .NET 7 的功能特性中，推出了更進一步的 NativeAOT，讓 .NET 開發者也能編譯成原生應用程式，讓我們的應用程式更快速的啟動，並且使用更少的記憶體。這場議程就來探究一下這項讓應用程式又小又快的 NativeAOT 特性吧。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 11, 30, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 12, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Hugh Huang",
                    Name = "Hugh Huang",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Hugh Huang.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "我不是在 Coding 就是在 Coding 的路上。曾任團隊 Tech lead，專注於使用 .NET 技術並透過 OOP、TDD、SBE 開發得「剛剛好」。也負責訂立團隊規範與流程，其他時間則是在當通靈王。",
                    Topic = "程式碼債台高築了嗎？快使用 SonarQube 做一波負債整合",
                    TopicOutline = "開發的路上一定會遇到技術債，很多時候他像地下錢莊，光是還利息就讓你喘不過氣，難得有時間看到滿滿的債務又不知從何處理，更不知道怎麼提出數據證明這些債務與還債的好處來說服你的老闆。是時候了解 SonarQube 以及他能夠為你帶來的好處了，它能夠為你分析原始碼品質、檢測安全漏洞、提出改善建議，更提供了報表讓你方便提出還債計畫。<br/>在這次的分享，你將了解:<br/>1. 甚麼是SonarQube<br/>2. SonarQube 能為你帶來甚麼好處<br/>3. 如何架設 SonarQube<br/>4. 如何在 CI 整合 SonarQube<br/>還債起頭難，你需要的是 - SonarQube！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 17, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 17, 30, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "EvanceKao",
                    Name = "Evance Kao",
                    JobTitle = "91APP 資深後端工程師",
                    PictureUrl ="./img/speakers/Evance Kao.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "從天氣預報斜槓到軟體開發，從每天看雲轉變為服務上雲，喜歡從不同角度看同一件事情、抽象化各種業務邏輯、製造小輪子以揣摩米其林輪胎的設計。大多鑽研 DevOps (專注在 CI/CD)、系統架構與雲端服務，實務上則有 4 年以上的雲端架構設計、開發及維護經驗，並具有公有雲助理級證照。現任於 91APP 架構設計部，嘗試以多元角度從上而下再從下而上協助團隊成功。",
                    Topic = "更好的開發體驗 - 建造 SDK 接上 API 的腿",
                    TopicOutline = "你的服務推出了好的 API，下一步該如何讓開發者在使用你的服務時，有更好的開發體驗呢？除了文件、教育訓練及不斷地協作之外，提供 (API client) SDK 給開發者們使用，是一個常見且有效的做法。<br/><br/>在這個場次，我將分享在大型團隊中設計及開發 SDK 的經驗，透過我們實務上遇到的問題，引入 SDK 設計的多項議題，包含：<br/>1. SDK 的初始化<br/>2. SDK 版本管理<br/>3. 讓開發者清楚的知道使用 SDK 時發生了甚麼事情<br/>4. 藉由 SDK 提高呼叫 API 的可靠性<br/>5. 藉由 SDK 提供使用 API 的最佳實踐",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2022, 12, 17, 0, 0, 0),
                    SessionEnd = new DateTime(2022, 12, 17, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
            };

            return speakers;
        }
    }
}
